#!/bin/sh

# This file runs when logging into a graphical session
# xwallpaper --maximize ~/.config/wallpaper.jpg

export TERMINAL=st
export BROWSER=brave
export EDITOR=nvim

wal --backend haishoku -i ~/pix/wal/alena-aenami-wait.jpg
~/.local/bin/remaps &
unclutter -idle 3 &
