#!/bin/sh

# This file runs when logging into a graphical session
# xwallpaper --maximize ~/.config/wallpaper.jpg

export TERMINAL=st
export BROWSER=chromium
export EDITOR=nvim

feh --bg-scale $HOME/pix/wal/blue_unicat.png &

remaps &
picom &
dunst &
unclutter -idle 3 &
