require "options"
require "plugins"

require "plugins.alpha"
require "plugins.autopairs"
require "plugins.bufferline"
require "plugins.cmp"
require "plugins.comment"
require "plugins.impatient"
require "plugins.lightbulb"
require "plugins.lsp"
require "plugins.lualine"
require "plugins.neo-tree"
require "plugins.project"
require "plugins.telescope"
require "plugins.toggleterm"
require "plugins.treesitter"
require "plugins.whichkey"
