#! /bin/sh

xrdb ~/.Xresources

# Configure monitors
xrandr --output DP-0 --mode 2560x1440 --rate 165 --primary --output HDMI-0 --left-of DP-1 --mode 1920x1080 --rotate right --rate 75 &

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
# pgrep -x picom > /dev/null || picom &
pgrep -x xcompmgr > /dev/null || xcompmgr &
pgrep -x dunst > /dev/null || dunst &
pgrep -x unclutter > /dev/null || unclutter --timeout 3 &

# pgrep -x pipewire > /dev/null || pipewire &
# pgrep -x pipewire-pulse > /dev/null || pipewire-pulse &
# pgrep -x wireplumber > /dev/null || wireplumber &

~/.config/polybar/launch.sh &

# Configure desktops
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9

# Source colors
# . "${HOME}/.cache/wal/colors.sh"

# Configure bpswm
bspc config normal_border_color "$color0"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled

xsetroot -cursor_name left_ptr &

# Set mouse sens
xinput set-prop 11 "libinput Accel Speed" -0.4

# Keyboard layout
~/.local/bin/remaps &

# Set the wallpaper
# wal -R
feh --bg-fill ~/pix/wal/marek-piwnicki-XzZ0qzvQcnw-unsplash.jpg
