#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
pgrep -x unclutter > /dev/null || unclutter --timeout 3 &
~/.config/polybar/launch.sh &

# Configure monitors
xrandr --output DP-0 --mode 2560x1440 --rate 165 --primary --output HDMI-0 --left-of DP-0 --rotate right --rate 75 --mode 1920x1080 &

# Configure desktops
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9

# Source colors
. "${HOME}/.cache/wal/colors.sh"

# Configure bpswm
bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config presel_feedback_color "$color1"

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled

xsetroot -cursor_name left_ptr &

# Set mouse sens
xinput set-prop 9 "libinput Accel Speed" -0.4
4

# Keyboard layout
/home/nico/.local/bin/remaps &

# Set the wallpaper
wal -R

# Check for new system updates
if [ $(yay -Qu | wc -l) -gt 0 ]
then
    notify-send "Updates availible!" "$(yay -Qu | wc -l) Updates are availible"
fi
