#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
pgrep -x polybar > /dev/null || polybar bar &
pgrep -x unclutter > /dev/null || unclutter --timeout 3 &

xrandr --output DP-0 --mode 2560x1440 --rate 165 --primary --output HDMI-0 --left-of DP-0 --rotate right --rate 75 --mode 1920x1080 &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled

xsetroot -cursor_name left_ptr &

xinput set-prop 9 298 -0.7 &

/home/nico/.local/bin/remaps &
/home/nico/.local/bin/wal -R &
