#! /bin/sh

# fix polybar fonts
/home/nico/repos/polybar-orig/setup.sh

# mount server
curlftpfs ni5617995_1:iprTk9eP@ms2925.gamedata.io ~/minecraft_server/

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
pgrep -x unclutter > /dev/null || unclutter --timeout 3 &

xrandr --output DP-0 --mode 2560x1440 --rate 165 --primary --output HDMI-0 --left-of DP-0 --rotate right --rate 75 --mode 1920x1080 &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 -d 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled

xsetroot -cursor_name left_ptr &

xinput set-prop 10 "libinput Accel Speed" -0.5 &

/home/nico/.config/polybar/material/scripts/pywal.sh /home/nico/pix/wal
pgrep -x polybar > /dev/null || ~/.config/polybar/material/launch.sh &

/home/nico/.local/bin/remaps &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
