#!/bin/bash

pstatus="$(playerctl -p spotify status 2> /dev/null)"

if [[ "$pstatus" == "" ]]; then
    exit
fi

title="$(playerctl -p spotify metadata xesam:title 2> /dev/null)"
artist="$(playerctl -p spotify metadata xesam:artist 2> /dev/null)"

get_data ()
{
    icon=""

    case "$pstatus" in
        "Paused") text="$title - $artist  "
        ;;
        "Playing") text="$title - $artist"
        ;;
        *) test="None"
        ;;
    esac
}

get_data
echo "$icon  $text"
