#!/bin/bash

# Extract the temperature from the data
TEMP="$(curl -s 'wttr.in/?format=%f' | sed 's/+//g')"

# Extract the condition from the data
CONDITION="$(curl -s 'wttr.in/?format=%C')"

# Output the appropriate icon based on the condition
case $CONDITION in
	"Light Rain")
		echo -e "\uf74e $TEMP"
		;;
	"Heavy Rain")
		echo -e "\uf7a8 $TEMP"
		;;
	"Cloudy")
		echo -e "\uf74d $TEMP"
		;;
	"Clear")
		echo -e "\uf185 $TEMP"
		;;
	"Partly cloudy")
		echo -e "  $TEMP"
		;;
	*)
		echo -e "\uf2db $CONDITION $TEMP"
		;;
esac
