#!/bin/sh

# This file runs when logging into a graphical session
# xwallpaper --maximize ~/.config/wallpaper.jpg

# Export environment variables
export TERMINAL=st
export BROWSER=chromium
export EDITOR=nvim

# dwmblocks &
# remaps &
# picom &
# dunst &
# unclutter -idle 3 &
